// src/tokenizer/unicode_ranges.h -- Unicode classes for the pre-tokeniser.
//
// The reference pre-tokeniser is a Unicode regex (\p{L}, \p{M}, \p{N}, \s).
// This header is the smallest thing that can answer it without linking ICU: a
// generated table of codepoint ranges and one lookup. Generated by
// tools/gen_unicode_ranges.py -- regenerate rather than edit.
#pragma once

#include <cstdint>

namespace knj {

// Letter is \p{L}, Mark is \p{M}, Number is \p{N}, Space is \s (Zs/Zl/Zp
// plus the ASCII controls); everything else -- punctuation, symbols, emoji -- is
// Other. Letter and Mark are separate because the two pre-tokenisers differ
// exactly there: `qwen2` matches [\p{L}]+ and treats a mark as punctuation,
// `qwen35` matches [\p{L}\p{M}]+ and lets a mark join the letter run.
enum class UnicodeClass { Other, Letter, Mark, Number, Space };

UnicodeClass unicode_class(uint32_t cp);

}  // namespace knj
