#!/usr/bin/env python3
"""Extract IQ codebook tables verbatim from ggml's ggml-common.h.

The engine's IQ decoders index these tables exactly as ggml's scalar
dequantizers do (byte-cast of packed u64/u32 entries, little-endian).
Hand-copying 2048-entry tables is how transcription errors happen, so the
tables are copied mechanically: this script parses the GGML_TABLE_BEGIN
blocks and emits src/loader/iq_grids.h with knj_ names.

Usage:
  python tools/extract_iq_grids.py <ggml-common.h> <out-header>
Provenance is written into the header (source path + sha256).
"""
import hashlib
import re
import sys

WANT = [
    ("uint8_t", "kmask_iq2xs", 8, "knj_kmask_iq2xs"),
    ("uint8_t", "ksigns_iq2xs", 128, "knj_ksigns_iq2xs"),
    ("uint64_t", "iq2xxs_grid", 256, "knj_iq2xxs_grid"),
    ("uint64_t", "iq2xs_grid", 512, "knj_iq2xs_grid"),
    ("uint64_t", "iq2s_grid", 1024, "knj_iq2s_grid"),
    ("uint32_t", "iq3xxs_grid", 256, "knj_iq3xxs_grid"),
    ("uint32_t", "iq3s_grid", 512, "knj_iq3s_grid"),
    ("int8_t", "kvalues_iq4nl", 16, "knj_kvalues_iq4nl"),
    ("int8_t", "kvalues_fp4", 16, "knj_kvalues_fp4"),
    ("uint64_t", "iq1s_grid", 2048, "knj_iq1s_grid"),
]


def extract(src, ctype, name, count):
    m = re.search(
        r"GGML_TABLE_BEGIN\(\s*" + re.escape(ctype) + r"\s*,\s*" + re.escape(name)
        + r"\s*,[^)]*\)(.*?)GGML_TABLE_END\(\)",
        src, re.S,
    )
    if not m:
        raise SystemExit(f"table {name} not found")
    body = m.group(1)
    nums = re.findall(r"0[xX][0-9a-fA-F]+|-?\d+", body)
    if len(nums) != count:
        raise SystemExit(f"table {name}: want {count} entries, found {len(nums)}")
    return nums


def main():
    src_path, out_path = sys.argv[1], sys.argv[2]
    with open(src_path) as f:
        src = f.read()
    sha = hashlib.sha256(src.encode()).hexdigest()
    tables = [(c, n, k, extract(src, c, n, cnt)) for c, n, cnt, k in WANT]
    with open(out_path, "w") as f:
        f.write("// GENERATED by tools/extract_iq_grids.py -- do not hand-edit.\n")
        f.write(f"// Source: {src_path}\n// sha256: {sha}\n")
        f.write("// These are ggml's IQ codebooks, byte-identical. The engine's\n")
        f.write("// IQ decoders index them exactly as ggml's scalar dequantizers\n")
        f.write("// do (byte-cast of the packed entries, little-endian).\n#pragma once\n\n#include <cstdint>\n\nnamespace knj {\n")
        for ctype, _name, knj, nums in tables:
            f.write(f"\nstatic const {ctype} {knj}[{len(nums)}] = {{\n")
            for i in range(0, len(nums), 4):
                f.write("    " + ", ".join(nums[i:i + 4]) + ",\n")
            f.write("};\n")
        f.write("\n}  // namespace knj\n")
    print(f"wrote {out_path}: {sum(len(t[3]) for t in tables)} entries")


if __name__ == "__main__":
    main()
