#!/usr/bin/env python3
"""Generate the Unicode class tables the tokenizer's pre-tokeniser needs.

The reference pre-tokeniser regex is Unicode, not byte-level:

    (?:'[sS]|'[tT]|'[rR][eE]|'[vV][eE]|'[mM]|'[lL][lL]|'[dD])
  | [^\\r\\n\\p{L}\\p{N}]?[\\p{L}\\p{M}]+
  | \\p{N}
  |  ?[^\\s\\p{L}\\p{M}\\p{N}]+[\\r\\n]*
  | \\s*[\\r\\n]+
  | \\s+(?!\\S)
  | \\s+

so "is this codepoint a letter, a mark, a number, a space, or none of those"
decides where a chunk boundary falls -- and a chunk boundary decides which BPE
merges are even possible. Classifying bytes (`>= 0x80` is a letter) gets both
CJK and emoji wrong: it joins an emoji to the word before it, where the
reference treats it as a symbol.

The classes come from Python's `unicodedata`, which carries the Unicode
Character Database, and are emitted as sorted codepoint ranges with a binary
search. The table is GENERATED: edit this script and regenerate, do not edit the
.cpp by hand. `tools/tok_crosscheck.py` is what proves the result, string by
string, against llama.cpp.

    python tools/gen_unicode_ranges.py            # writes the .cpp next to this tool
"""
import os
import sys
import unicodedata

# \p{L} = Lu Ll Lt Lm Lo ; \p{M} = Mn Mc Me ; \p{N} = Nd Nl No.
#
# LETTER and MARK are separate tables, because the two pre-tokenisers this engine
# implements differ in exactly one place: `qwen2` matches `[\p{L}]+` and
# `[^\s\p{L}\p{N}]+`, so a combining mark is *not* part of a letter run, while
# `qwen35` matches `[\p{L}\p{M}]+` and `[^\s\p{L}\p{M}\p{N}]+`, so a mark joins
# the run. Merging them into one class (which this script used to do) implements
# only the qwen35 rule while pretending to implement both.
LETTER = ("Lu", "Ll", "Lt", "Lm", "Lo")
MARK = ("Mn", "Mc", "Me")
NUMBER = ("Nd", "Nl", "No")

# Rust's and PCRE's `\s` is the Zs/Zl/Zp categories plus the ASCII/ISO-8859
# controls that Unicode counts as whitespace. Written out rather than derived,
# because these nine ranges ARE the definition of \s in the reference engines.
SPACE = [
    (0x0009, 0x000D),  # \t \n \v \f \r
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
]


def ranges_for(categories):
    out = []
    lo = None
    for cp in range(0x110000):
        hit = unicodedata.category(chr(cp)) in categories
        if hit and lo is None:
            lo = cp
        elif not hit and lo is not None:
            out.append((lo, cp - 1))
            lo = None
    if lo is not None:
        out.append((lo, 0x10FFFF))
    return out


def merge(rs):
    """Sort and coalesce adjacent ranges, so the table is as small as it can be."""
    rs = sorted(rs)
    out = []
    for lo, hi in rs:
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def emit(name, rs, out):
    out.append("const Range k%s[] = {" % name)
    line = "   "
    for lo, hi in rs:
        item = " {0x%X, 0x%X}," % (lo, hi)
        if len(line) + len(item) > 96:
            out.append(line)
            line = "   "
        line += item
    out.append(line)
    out.append("};")
    out.append("const size_t k%s_n = sizeof(k%s) / sizeof(k%s[0]);" % (name, name, name))
    out.append("")
    return len(rs)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    letters = merge(ranges_for(LETTER))
    marks = merge(ranges_for(MARK))
    numbers = merge(ranges_for(NUMBER))
    spaces = merge(SPACE)
    print("ranges: letter %d, mark %d, number %d, space %d (Unicode %s)"
          % (len(letters), len(marks), len(numbers), len(spaces),
             unicodedata.unidata_version))

    out = []
    out.append("// src/tokenizer/unicode_ranges.cpp -- GENERATED by tools/gen_unicode_ranges.py.")
    out.append("//")
    out.append("// Do not edit by hand: regenerate with")
    out.append("//     python tools/gen_unicode_ranges.py")
    out.append("// and re-run tools/tok_crosscheck.py, which is what proves the result.")
    out.append("//")
    out.append("// Unicode %s, from Python's unicodedata. \\p{L} and \\p{M} are SEPARATE"
               % unicodedata.unidata_version)
    out.append("// classes because the two pre-tokenisers differ there: `qwen2` matches")
    out.append("// [\\p{L}]+ (a mark is punctuation), `qwen35` matches [\\p{L}\\p{M}]+ (a mark")
    out.append("// joins the letter run). \\p{N} is its own class, \\s is the Zs/Zl/Zp set plus")
    out.append("// the ASCII controls, written out in the generator.")
    out.append('#include "src/tokenizer/unicode_ranges.h"')
    out.append("")
    out.append("namespace knj {")
    out.append("namespace {")
    out.append("")
    out.append("struct Range { uint32_t lo, hi; };")
    out.append("")
    nl = emit("Letter", letters, out)
    nm = emit("Mark", marks, out)
    nn = emit("Number", numbers, out)
    ns = emit("Space", spaces, out)
    out.append("bool in(const Range* r, size_t n, uint32_t cp) {")
    out.append("  size_t lo = 0, hi = n;")
    out.append("  while (lo < hi) {")
    out.append("    const size_t mid = lo + (hi - lo) / 2;")
    out.append("    if (cp < r[mid].lo) hi = mid;")
    out.append("    else if (cp > r[mid].hi) lo = mid + 1;")
    out.append("    else return true;")
    out.append("  }")
    out.append("  return false;")
    out.append("}")
    out.append("")
    out.append("}  // namespace")
    out.append("")
    out.append("UnicodeClass unicode_class(uint32_t cp) {")
    out.append("  // Space first: the whitespace ranges are ten entries and the letter table is")
    out.append("  // hundreds, so this order is the cheap one for real text.")
    out.append("  if (in(kSpace, kSpace_n, cp)) return UnicodeClass::Space;")
    out.append("  if (in(kNumber, kNumber_n, cp)) return UnicodeClass::Number;")
    out.append("  if (in(kLetter, kLetter_n, cp)) return UnicodeClass::Letter;")
    out.append("  if (in(kMark, kMark_n, cp)) return UnicodeClass::Mark;")
    out.append("  return UnicodeClass::Other;")
    out.append("}")
    out.append("")
    out.append("}  // namespace knj")
    out.append("")

    header = os.path.join(root, "src", "tokenizer", "unicode_ranges.h")
    with open(header, "w", encoding="utf-8", newline="\n") as fh:
        fh.write('''// src/tokenizer/unicode_ranges.h -- Unicode classes for the pre-tokeniser.
//
// The reference pre-tokeniser is a Unicode regex (\\p{L}, \\p{M}, \\p{N}, \\s).
// This header is the smallest thing that can answer it without linking ICU: a
// generated table of codepoint ranges and one lookup. Generated by
// tools/gen_unicode_ranges.py -- regenerate rather than edit.
#pragma once

#include <cstdint>

namespace knj {

// Letter is \\p{L}, Mark is \\p{M}, Number is \\p{N}, Space is \\s (Zs/Zl/Zp
// plus the ASCII controls); everything else -- punctuation, symbols, emoji -- is
// Other. Letter and Mark are separate because the two pre-tokenisers differ
// exactly there: `qwen2` matches [\\p{L}]+ and treats a mark as punctuation,
// `qwen35` matches [\\p{L}\\p{M}]+ and lets a mark join the letter run.
enum class UnicodeClass { Other, Letter, Mark, Number, Space };

UnicodeClass unicode_class(uint32_t cp);

}  // namespace knj
''')
    cpp = os.path.join(root, "src", "tokenizer", "unicode_ranges.cpp")
    with open(cpp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))
    print("wrote %s" % header)
    print("wrote %s (%d letter, %d mark, %d number, %d space ranges)"
          % (cpp, nl, nm, nn, ns))
    return 0


if __name__ == "__main__":
    sys.exit(main())
