#!/usr/bin/env python3

"""5000-prompt tokenizer fuzz, seeded and reproducible.

Each prompt is generated by the fuzz mode of tools/tok_crosscheck.py, written to
its own file, tokenized by both kanjoos-run and llama-tokenize, and compared the
same way the hand-written set is: a merge-boundary difference (differs from llama
in no-parse-special mode) is the failure; a policy difference (differs only with
special parsing) is reported but not a failure.

Run with KNJ_TOK_MODEL, KNJ_LLAMA_TOKENIZE and KNJ_ENGINE set (the same as the
suite gate).  Logs to records/, one file per seed; appends if the file exists.

Exit 0 when no merge-boundary difference survives across all seeds; 1 when one
does; 3 when a prerequisite is missing (NOT RUN).

This is a long-running gate. It is meant to be run in the background while the
rest of the suite moves, and its log inspected on completion. It does not replace
the 25-string hand set or the separator sweep — it covers the broad, unspecific
input surface those bounds cannot reach.

A campaign does not PASS on the strength of a summary line that was never emitted.
If a seed aborts (rc 143 / 3221225794 / loader failure) or if the single summary
line the cross-check prints is missing, that seed compared zero prompts and the
harness must say so — `total_prompts=0` is the failure mode here, not a pass.

A seed that prints some prompts and then dies is worse than incomplete: it is a
FAIL, because the campaign does not know whether the uncompared prompts would have
changed the verdict. The unresolved cause of the death is a separate defect; the
tokenizer result for the prompts that *did* compare is reported honestly, and the
campaign does not fold a crash into the same bucket as a mere missing summary line.

When the cross-check runs prompts but the ENGINE dies before the cross-check can
finish, the campaign now classifies that as ENGINE-UNREACHABLE. That is a distinct
outcome from a missing summary line: in the engine-unreachable case the prompts up
to the crash were actually compared, so the numbers for those prompts are known and
reported; in the missing-summary-line case no prompt-comparison result exists and
the campaign cannot honestly claim any prompts were compared.

Same seed, fewer prompts (the common case this harness actually used for):
  python tools/tok_fuzz_campaign.py --seeds 1 --per-seed 60 --fuzz-seed 11
The cross-check is invoked with `--fuzz-bound`, so a re-run with a smaller --per-seed
is a prefix of the full run (same sequence, just truncated), not a different run.

The campaign invokes the cross-check with `--fuzz-min-fail <per_seed+1>` so that
the tool's own exit status is consistent with the campaign's: a run that compares
fewer than the requested prompts cannot exit 0 on the strength of the subset it
did compare.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CROSS = os.path.join(ROOT, "tools", "tok_crosscheck.py")
RECORDS = os.path.join(ROOT, "records", "tok-fuzz-5000")

DEFAULT_SEEDS = (1, 2, 3)
DEFAULT_PER_SEED = 5000
DEFAULT_FUZZ_SEED = 1

SUMMARY_RE = re.compile(
    r"(?P<n>\d+)/(?P<m>\d+)\s+strings\s+identical,\s+"
    r"(?P<p>\d+)\s+policy\s+difference\(s\),\s+"
    r"(?P<b>\d+)\s+merge-boundary\s+difference\(s\),"
    r"(?:\s+(?P<t>\d+)\s+tokens\s+compared)?"
)


def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def run(cmd: list[str], env: dict) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=ROOT, env=env, capture_output=True,
                          text=True, errors="replace")


def per_seed_from_log(stdout: str, per_seed: int) -> dict:
    """Return the per-seed totals the report should use.

    The campaign drives one cross-check invocation per seed with:
      --fuzz <per_seed> --fuzz-seed <fuzz_seed> --fuzz-bound <per_seed>

    That invocation builds ONE strings list [hand set] + [fuzz], and prints
    exactly ONE summary line at the end, in this canonical form (as of the
    campaign's pinned cross-check revision):

      N/M strings identical, P policy difference(s),
      B merge-boundary difference(s), T tokens compared

    The fuzz prompts live in the tail of that list, and the tool's
    `fuzz_verbose` machinery labels which fail came from a fuzz prompt. The
    campaign does not re-issue the cross-check a second time to produce a
    separate "fuzz-only" line. If a future revision of the cross-check adds an
    explicit second summary line, the campaign prefers the last matching line
    (already the behaviour below), so the parser keeps working.

    Field mapping:
      ok = N,  cross_check_total = M,  policy = P,  boundary = B,  tokens = T.
    i.e. ok = strings identical, cross_check_total = of N/M, policy = policy
    difference count, boundary = merge-boundary difference count, tokens =
    tokens compared.

    If no matching summary line is present, the seed compared zero prompts from
    the cross-check's point of view, and the campaign treats that as a failure
    mode (`complete=False`), not as a pass with zero differences.
    """
    lines = [ln for ln in stdout.splitlines()
             if "strings identical" in ln and "merge-boundary" in ln]
    if not lines:
        return {"ok": 0, "boundary": 0, "policy": 0, "tokens": 0,
                "complete": False, "cross_check_total": per_seed}
    line = lines[-1]
    m_text = SUMMARY_RE.search(line)
    if not m_text:
        return {"ok": 0, "boundary": 0, "policy": 0, "tokens": 0,
                "complete": True, "cross_check_total": per_seed}
    vals = {k: int(m_text.group(k)) for k in ("n", "m", "p", "b")}
    vals["t"] = int(m_text.group("t")) if m_text.group("t") else 0
    n = vals["n"]
    m = vals["m"]
    p = vals["p"]
    b = vals["b"]
    t = vals["t"]
    return {"ok": n,
            "boundary": b,
            "policy": p,
            "tokens": t,
            "complete": True,
            "cross_check_total": m}


def _log_tail(path: str, size: int = 2000) -> str:
    tail = ""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            fh.seek(0, os.SEEK_END)
            file_size = fh.tell()
            if file_size > size:
                fh.seek(max(0, file_size - size), os.SEEK_SET)
            tail = fh.read()
    except OSError:
        pass
    return tail


def _looks_like_crash_tail(tail: str) -> bool:
    return any(s in tail for s in (
        "rc 3221225794", "rc 3221225785", "rc 143",
        "tok_crosscheck:", "Segmentation fault", "Access violation", "llvm",
    ))


def _looks_like_engine_crash_tail(tail: str) -> bool:
    return any(s in tail for s in (
        "rc 3221225785", "rc 143", "Segmentation fault",
        "Access violation", "tok_crosscheck: llama-tokenize printed no id list",
    ))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="5000-prompt tokenizer fuzz, seeded and reproducible",
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seeds", default=None, type=int, nargs="+",
                    help="seed list (default: 1 2 3; example: --seeds 1)")
    ap.add_argument("--per-seed", default=None, type=int,
                    help="prompts per seed (default: 5000; example: --per-seed 60)")
    ap.add_argument("--fuzz-seed", default=None, type=int,
                    help="fuzz prompt seed when --seeds is a single seed "
                         "(default: 1; example: --fuzz-seed 11)")
    ap.add_argument("--no-fuzz-verbose", action="store_true", default=False,
                    help="suppress the per-prompt fuzz output (for a smaller log)")
    args = ap.parse_args(argv)

    if not os.path.isfile(CROSS):
        print("NOT RUN: tools/tok_crosscheck.py missing", file=sys.stderr)
        return 3

    model = os.environ.get("KNJ_TOK_MODEL")
    tokenize = os.environ.get("KNJ_LLAMA_TOKENIZE")
    engine = os.environ.get("KNJ_ENGINE")
    if not model or not tokenize or not engine:
        print("NOT RUN: set KNJ_TOK_MODEL, KNJ_LLAMA_TOKENIZE, KNJ_ENGINE", file=sys.stderr)
        return 3
    if not os.path.isfile(model) or not os.path.isfile(tokenize) or not os.path.isfile(engine):
        print("NOT RUN: one of the three inputs is not a file", file=sys.stderr)
        return 3

    seeds = tuple(args.seeds) if args.seeds is not None else DEFAULT_SEEDS
    per_seed = int(args.per_seed) if args.per_seed is not None else DEFAULT_PER_SEED
    fuzz_seed = int(args.fuzz_seed) if args.fuzz_seed is not None else DEFAULT_FUZZ_SEED
    fuzz_verbose = not args.no_fuzz_verbose

    run_meta = {
        "crosscheck_sha256": sha256_bytes(open(CROSS, "rb").read())[:24],
        "crosscheck_display_sha256": sha256_bytes(open(CROSS, "rb").read())[:12],
        "model": model,
        "llama_tokenize": tokenize,
        "engine": engine,
        "fuzz_seed": fuzz_seed,
        "per_seed": per_seed,
        "seeds": seeds,
    }

    os.makedirs(RECORDS, exist_ok=True)
    env = os.environ.copy()
    if "KNJ_MINGW_BIN" in env:
        mingw = env["KNJ_MINGW_BIN"]
    else:
        mingw = "/c/Strawberry/c/bin"
    if os.path.isfile(os.path.join(mingw, "libstdc++-6.dll")):
        env["PATH"] = mingw + os.pathsep + env.get("PATH", "")

    total_ok = 0
    total_boundary = 0
    total_policy = 0
    total_tokens = 0
    total_prompts = 0
    total_unfinished = 0

    per_seed_rows: list[dict] = []
    for seed in seeds:
        log_name = f"seed{seed}-{per_seed}.log" if per_seed else f"seed{seed}.log"
        log_path = os.path.join(RECORDS, log_name)
        print(f"seed {seed}: logging to {log_path}")
        with open(log_path, "a", encoding="utf-8") as log:
            log.write(f"\n===== seed {seed}, {per_seed} prompts, "
                      f"{run_meta['crosscheck_sha256']} =====\n")
            for k in ("model", "llama_tokenize", "engine"):
                log.write(f"{k}={run_meta[k]}\n")
            log.write(f"KNJ_TOK_MODEL={os.environ.get('KNJ_TOK_MODEL')}\n")
            log.write(f"KNJ_LLAMA_TOKENIZE={os.environ.get('KNJ_LLAMA_TOKENIZE')}\n")
            log.write(f"KNJ_ENGINE={os.environ.get('KNJ_ENGINE')}\n")
            log.write(f"fuzz_seed={fuzz_seed}  per_seed={per_seed}\n\n")

            cmd = [sys.executable, CROSS, "--model", model, "--engine", engine,
                   "--llama-tokenize", tokenize,
                   "--fuzz", str(per_seed), "--fuzz-seed", str(fuzz_seed),
                   "--fuzz-bound", str(per_seed),
                   "--fuzz-min-fail", str(per_seed + 1)]
            if fuzz_verbose:
                cmd.append("--fuzz-verbose")
            p = run(cmd, env)
            log.write(p.stdout)
            if p.stderr:
                log.write("\n--- stderr ---\n")
                log.write(p.stderr)
            log.write(f"\nrc={p.returncode}\n")

            row = per_seed_from_log(p.stdout, per_seed)
            row["seed"] = seed
            row["rc"] = p.returncode
            row["log"] = log_path
            per_seed_rows.append(row)

            if not row["complete"]:
                tail = _log_tail(log_path)
                crashy = _looks_like_crash_tail(tail)
                engine_crashy = _looks_like_engine_crash_tail(tail)
                if crashy and engine_crashy:
                    completed_prompts = row["cross_check_total"] if row["complete"] else 0
                    if completed_prompts > 0:
                        print(f"seed {seed}: ENGINE-UNREACHABLE after "
                              f"{completed_prompts} of {per_seed} prompts — "
                              f"ok={row['ok']} boundary={row['boundary']} "
                              f"policy={row['policy']} tokens={row['tokens']} "
                              f"(rc={p.returncode}; treated as FAIL, not a partial pass; "
                              f"see {log_path})")
                    else:
                        print(f"seed {seed}: ENGINE-UNREACHABLE before any prompt "
                              f"comparison — rc={p.returncode} (treated as FAIL, not a "
                              f"partial pass; see {log_path})")
                    total_boundary += 1
                elif crashy:
                    completed_prompts = row["cross_check_total"] if row["complete"] else 0
                    if completed_prompts > 0:
                        print(f"seed {seed}: cross-check crashed after "
                              f"{completed_prompts} of {per_seed} prompts — "
                              f"ok={row['ok']} boundary={row['boundary']} "
                              f"policy={row['policy']} tokens={row['tokens']} "
                              f"(rc={p.returncode}; treated as FAIL, not a partial pass; "
                              f"see {log_path})")
                    else:
                        print(f"seed {seed}: cross-check crashed before it finished "
                              f"{per_seed} prompts — no prompt-comparisons logged "
                              f"(rc={p.returncode}; treated as FAIL, not a partial pass; "
                              f"see {log_path})")
                    total_boundary += 1
                else:
                    print(f"seed {seed}: no cross-check summary line in stdout — seed compared "
                          f"0 prompts (rc={p.returncode}; see {log_path})")
                    total_boundary += 1
            else:
                print(f"seed {seed}: ok={row['ok']} boundary={row['boundary']} "
                      f"policy={row['policy']} tokens={row['tokens']} "
                      f"(cross-check total {row['cross_check_total']})")

        total_ok += row["ok"]
        total_boundary += row["boundary"]
        total_policy += row["policy"]
        total_tokens += row["tokens"]
        if row["complete"]:
            total_prompts += per_seed
        else:
            total_unfinished += 1

    summary_path = os.path.join(RECORDS, "summary.txt")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(f"seeds={seeds}\n")
        f.write(f"prompts_per_seed={per_seed}\n")
        f.write(f"total_prompts={total_prompts}\n")
        f.write(f"total_unfinished={total_unfinished}\n")
        f.write(f"total_ok={total_ok}\n")
        f.write(f"total_policy={total_policy}\n")
        f.write(f"total_boundary={total_boundary}\n")
        f.write(f"total_tokens={total_tokens}\n")
        f.write(f"crosscheck_sha256={run_meta['crosscheck_sha256']}\n")
        f.write(f"crosscheck_display_sha256={run_meta['crosscheck_display_sha256']}\n")
        f.write(f"fuzz_seed={fuzz_seed}\n")
        f.write("\nper_seed:\n")
        for row in per_seed_rows:
            f.write(f"seed{row['seed']}: rc={row['rc']} ok={row['ok']} "
                    f"boundary={row['boundary']} policy={row['policy']} "
                    f"tokens={row['tokens']} complete={row['complete']} "
                    f"log={row['log']}\n")
        if total_boundary == 0 and total_unfinished == 0:
            f.write("VERDICT: PASS — no merge-boundary divergence survived, and every seed completed all requested prompts.\n")
        elif total_boundary == 0:
            f.write("VERDICT: INCOMPLETE — no merge-boundary divergence among the prompts that were actually compared, but "
                    f"{total_unfinished} seed(s) did not finish their full request (crashed or refused), "
                    f"so this is a partial result, not a pass.\n")
        else:
            f.write(f"VERDICT: FAIL — {total_boundary} merge-boundary difference(s) survived, or a seed did not complete.\n")

    print(f"\ntotal: {total_prompts} completed prompts, {total_ok} identical, "
          f"{total_policy} policy, {total_boundary} boundary, {total_tokens} tokens; "
          f"{total_unfinished} unfinished seed(s)")
    for row in per_seed_rows:
        print(f"seed {row['seed']}: rc={row['rc']} ok={row['ok']} boundary={row['boundary']} "
              f"policy={row['policy']} tokens={row['tokens']} complete={row['complete']} "
              f"log={row['log']}")
    if total_boundary:
        print("VERDICT: FAIL — merge-boundary divergence survives, or a seed did not complete.")
    elif total_unfinished:
        print("VERDICT: INCOMPLETE — no merge-boundary divergence among the prompts compared, "
              "but not every seed finished; this is a partial result, not a pass.")
    else:
        print("VERDICT: PASS — no merge-boundary divergence survived across all seeds.")
    return 1 if total_boundary else 0


if __name__ == "__main__":
    raise SystemExit(main())
